// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Peer struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Device               int32    `protobuf:"varint,3,opt,name=device,proto3" json:"device,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Peer) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Peer) GetDevice() int32 {
	if m != nil {
		return m.Device
	}
	return 0
}

func (m *Peer) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type Payload struct {
	MsgType              uint32   `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Extra                string   `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Payload) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Payload) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type ChatReq struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	NotStore             bool     `protobuf:"varint,2,opt,name=not_store,json=notStore,proto3" json:"not_store,omitempty"`
	Payload              *Payload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatReq) Reset()         { *m = ChatReq{} }
func (m *ChatReq) String() string { return proto.CompactTextString(m) }
func (*ChatReq) ProtoMessage()    {}
func (*ChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *ChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatReq.Unmarshal(m, b)
}
func (m *ChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatReq.Marshal(b, m, deterministic)
}
func (m *ChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatReq.Merge(m, src)
}
func (m *ChatReq) XXX_Size() int {
	return xxx_messageInfo_ChatReq.Size(m)
}
func (m *ChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatReq proto.InternalMessageInfo

func (m *ChatReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatReq) GetNotStore() bool {
	if m != nil {
		return m.NotStore
	}
	return false
}

func (m *ChatReq) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// server send a ack message to message sender ,tell he the msg_id and send_time generated by server
type ChatAck struct {
	MsgId                int64    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SendTime             int64    `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatAck) Reset()         { *m = ChatAck{} }
func (m *ChatAck) String() string { return proto.CompactTextString(m) }
func (*ChatAck) ProtoMessage()    {}
func (*ChatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *ChatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatAck.Unmarshal(m, b)
}
func (m *ChatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatAck.Marshal(b, m, deterministic)
}
func (m *ChatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatAck.Merge(m, src)
}
func (m *ChatAck) XXX_Size() int {
	return xxx_messageInfo_ChatAck.Size(m)
}
func (m *ChatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatAck.DiscardUnknown(m)
}

var xxx_messageInfo_ChatAck proto.InternalMessageInfo

func (m *ChatAck) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatAck) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

type ChatPush struct {
	MsgId                int64    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	SendTime             int64    `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Payload              *Payload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ChatType             ChatType `protobuf:"varint,6,opt,name=chat_type,json=chatType,proto3,enum=wire.ChatType" json:"chat_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatPush) Reset()         { *m = ChatPush{} }
func (m *ChatPush) String() string { return proto.CompactTextString(m) }
func (*ChatPush) ProtoMessage()    {}
func (*ChatPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *ChatPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatPush.Unmarshal(m, b)
}
func (m *ChatPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatPush.Marshal(b, m, deterministic)
}
func (m *ChatPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatPush.Merge(m, src)
}
func (m *ChatPush) XXX_Size() int {
	return xxx_messageInfo_ChatPush.Size(m)
}
func (m *ChatPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatPush.DiscardUnknown(m)
}

var xxx_messageInfo_ChatPush proto.InternalMessageInfo

func (m *ChatPush) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatPush) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChatPush) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatPush) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *ChatPush) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChatPush) GetChatType() ChatType {
	if m != nil {
		return m.ChatType
	}
	return ChatType_SELF
}

// this ack message is send by client ,not server
type ChatPushAck struct {
	MsgIds               []int64  `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatPushAck) Reset()         { *m = ChatPushAck{} }
func (m *ChatPushAck) String() string { return proto.CompactTextString(m) }
func (*ChatPushAck) ProtoMessage()    {}
func (*ChatPushAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *ChatPushAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatPushAck.Unmarshal(m, b)
}
func (m *ChatPushAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatPushAck.Marshal(b, m, deterministic)
}
func (m *ChatPushAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatPushAck.Merge(m, src)
}
func (m *ChatPushAck) XXX_Size() int {
	return xxx_messageInfo_ChatPushAck.Size(m)
}
func (m *ChatPushAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatPushAck.DiscardUnknown(m)
}

var xxx_messageInfo_ChatPushAck proto.InternalMessageInfo

func (m *ChatPushAck) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

type ChatSync struct {
	MsgId                int64      `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ChatType             ChatType   `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=wire.ChatType" json:"chat_type,omitempty"`
	To                   string     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Device               DeviceType `protobuf:"varint,4,opt,name=device,proto3,enum=wire.DeviceType" json:"device,omitempty"`
	SendTime             int64      `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Payload              *Payload   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChatSync) Reset()         { *m = ChatSync{} }
func (m *ChatSync) String() string { return proto.CompactTextString(m) }
func (*ChatSync) ProtoMessage()    {}
func (*ChatSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6}
}

func (m *ChatSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatSync.Unmarshal(m, b)
}
func (m *ChatSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatSync.Marshal(b, m, deterministic)
}
func (m *ChatSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatSync.Merge(m, src)
}
func (m *ChatSync) XXX_Size() int {
	return xxx_messageInfo_ChatSync.Size(m)
}
func (m *ChatSync) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatSync.DiscardUnknown(m)
}

var xxx_messageInfo_ChatSync proto.InternalMessageInfo

func (m *ChatSync) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ChatSync) GetChatType() ChatType {
	if m != nil {
		return m.ChatType
	}
	return ChatType_SELF
}

func (m *ChatSync) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatSync) GetDevice() DeviceType {
	if m != nil {
		return m.Device
	}
	return DeviceType_PHONE
}

func (m *ChatSync) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *ChatSync) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type LoginReq struct {
	GatewayId            string     `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	PeerId               string     `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	AppKey               string     `protobuf:"bytes,3,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Username             string     `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Device               DeviceType `protobuf:"varint,5,opt,name=device,proto3,enum=wire.DeviceType" json:"device,omitempty"`
	RemoteIp             string     `protobuf:"bytes,6,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *LoginReq) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *LoginReq) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetDevice() DeviceType {
	if m != nil {
		return m.Device
	}
	return DeviceType_PHONE
}

func (m *LoginReq) GetRemoteIp() string {
	if m != nil {
		return m.RemoteIp
	}
	return ""
}

type LoginAck struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	UserUid              string   `protobuf:"bytes,2,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *LoginAck) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type KickOut struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickOut) Reset()         { *m = KickOut{} }
func (m *KickOut) String() string { return proto.CompactTextString(m) }
func (*KickOut) ProtoMessage()    {}
func (*KickOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9}
}

func (m *KickOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickOut.Unmarshal(m, b)
}
func (m *KickOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickOut.Marshal(b, m, deterministic)
}
func (m *KickOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickOut.Merge(m, src)
}
func (m *KickOut) XXX_Size() int {
	return xxx_messageInfo_KickOut.Size(m)
}
func (m *KickOut) XXX_DiscardUnknown() {
	xxx_messageInfo_KickOut.DiscardUnknown(m)
}

var xxx_messageInfo_KickOut proto.InternalMessageInfo

func (m *KickOut) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type LogoutReq struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{10}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type Loc struct {
	Device               DeviceType `protobuf:"varint,1,opt,name=device,proto3,enum=wire.DeviceType" json:"device,omitempty"`
	PeerId               string     `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	GatewayId            string     `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Loc) Reset()         { *m = Loc{} }
func (m *Loc) String() string { return proto.CompactTextString(m) }
func (*Loc) ProtoMessage()    {}
func (*Loc) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{11}
}

func (m *Loc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loc.Unmarshal(m, b)
}
func (m *Loc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loc.Marshal(b, m, deterministic)
}
func (m *Loc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loc.Merge(m, src)
}
func (m *Loc) XXX_Size() int {
	return xxx_messageInfo_Loc.Size(m)
}
func (m *Loc) XXX_DiscardUnknown() {
	xxx_messageInfo_Loc.DiscardUnknown(m)
}

var xxx_messageInfo_Loc proto.InternalMessageInfo

func (m *Loc) GetDevice() DeviceType {
	if m != nil {
		return m.Device
	}
	return DeviceType_PHONE
}

func (m *Loc) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *Loc) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

type MultiChatReq struct {
	Receivers            []string `protobuf:"bytes,1,rep,name=receivers,proto3" json:"receivers,omitempty"`
	ChatType             ChatType `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=wire.ChatType" json:"chat_type,omitempty"`
	ChatUid              string   `protobuf:"bytes,3,opt,name=chat_uid,json=chatUid,proto3" json:"chat_uid,omitempty"`
	Payload              *Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiChatReq) Reset()         { *m = MultiChatReq{} }
func (m *MultiChatReq) String() string { return proto.CompactTextString(m) }
func (*MultiChatReq) ProtoMessage()    {}
func (*MultiChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{12}
}

func (m *MultiChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiChatReq.Unmarshal(m, b)
}
func (m *MultiChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiChatReq.Marshal(b, m, deterministic)
}
func (m *MultiChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiChatReq.Merge(m, src)
}
func (m *MultiChatReq) XXX_Size() int {
	return xxx_messageInfo_MultiChatReq.Size(m)
}
func (m *MultiChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_MultiChatReq proto.InternalMessageInfo

func (m *MultiChatReq) GetReceivers() []string {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *MultiChatReq) GetChatType() ChatType {
	if m != nil {
		return m.ChatType
	}
	return ChatType_SELF
}

func (m *MultiChatReq) GetChatUid() string {
	if m != nil {
		return m.ChatUid
	}
	return ""
}

func (m *MultiChatReq) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type MultiChatPush struct {
	MsgId                int64    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	ChatType             ChatType `protobuf:"varint,3,opt,name=chat_type,json=chatType,proto3,enum=wire.ChatType" json:"chat_type,omitempty"`
	ChatUid              string   `protobuf:"bytes,4,opt,name=chat_uid,json=chatUid,proto3" json:"chat_uid,omitempty"`
	SendTime             int64    `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Payload              *Payload `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiChatPush) Reset()         { *m = MultiChatPush{} }
func (m *MultiChatPush) String() string { return proto.CompactTextString(m) }
func (*MultiChatPush) ProtoMessage()    {}
func (*MultiChatPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{13}
}

func (m *MultiChatPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiChatPush.Unmarshal(m, b)
}
func (m *MultiChatPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiChatPush.Marshal(b, m, deterministic)
}
func (m *MultiChatPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiChatPush.Merge(m, src)
}
func (m *MultiChatPush) XXX_Size() int {
	return xxx_messageInfo_MultiChatPush.Size(m)
}
func (m *MultiChatPush) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiChatPush.DiscardUnknown(m)
}

var xxx_messageInfo_MultiChatPush proto.InternalMessageInfo

func (m *MultiChatPush) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MultiChatPush) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MultiChatPush) GetChatType() ChatType {
	if m != nil {
		return m.ChatType
	}
	return ChatType_SELF
}

func (m *MultiChatPush) GetChatUid() string {
	if m != nil {
		return m.ChatUid
	}
	return ""
}

func (m *MultiChatPush) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *MultiChatPush) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PushConfirm struct {
	MsgIds               []int64  `protobuf:"varint,1,rep,packed,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushConfirm) Reset()         { *m = PushConfirm{} }
func (m *PushConfirm) String() string { return proto.CompactTextString(m) }
func (*PushConfirm) ProtoMessage()    {}
func (*PushConfirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{14}
}

func (m *PushConfirm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushConfirm.Unmarshal(m, b)
}
func (m *PushConfirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushConfirm.Marshal(b, m, deterministic)
}
func (m *PushConfirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushConfirm.Merge(m, src)
}
func (m *PushConfirm) XXX_Size() int {
	return xxx_messageInfo_PushConfirm.Size(m)
}
func (m *PushConfirm) XXX_DiscardUnknown() {
	xxx_messageInfo_PushConfirm.DiscardUnknown(m)
}

var xxx_messageInfo_PushConfirm proto.InternalMessageInfo

func (m *PushConfirm) GetMsgIds() []int64 {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

type PushConfirmAck struct {
	Affected             int32    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushConfirmAck) Reset()         { *m = PushConfirmAck{} }
func (m *PushConfirmAck) String() string { return proto.CompactTextString(m) }
func (*PushConfirmAck) ProtoMessage()    {}
func (*PushConfirmAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{15}
}

func (m *PushConfirmAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushConfirmAck.Unmarshal(m, b)
}
func (m *PushConfirmAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushConfirmAck.Marshal(b, m, deterministic)
}
func (m *PushConfirmAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushConfirmAck.Merge(m, src)
}
func (m *PushConfirmAck) XXX_Size() int {
	return xxx_messageInfo_PushConfirmAck.Size(m)
}
func (m *PushConfirmAck) XXX_DiscardUnknown() {
	xxx_messageInfo_PushConfirmAck.DiscardUnknown(m)
}

var xxx_messageInfo_PushConfirmAck proto.InternalMessageInfo

func (m *PushConfirmAck) GetAffected() int32 {
	if m != nil {
		return m.Affected
	}
	return 0
}

func init() {
	proto.RegisterType((*Peer)(nil), "wire.Peer")
	proto.RegisterType((*Payload)(nil), "wire.Payload")
	proto.RegisterType((*ChatReq)(nil), "wire.ChatReq")
	proto.RegisterType((*ChatAck)(nil), "wire.ChatAck")
	proto.RegisterType((*ChatPush)(nil), "wire.ChatPush")
	proto.RegisterType((*ChatPushAck)(nil), "wire.ChatPushAck")
	proto.RegisterType((*ChatSync)(nil), "wire.ChatSync")
	proto.RegisterType((*LoginReq)(nil), "wire.LoginReq")
	proto.RegisterType((*LoginAck)(nil), "wire.LoginAck")
	proto.RegisterType((*KickOut)(nil), "wire.KickOut")
	proto.RegisterType((*LogoutReq)(nil), "wire.LogoutReq")
	proto.RegisterType((*Loc)(nil), "wire.Loc")
	proto.RegisterType((*MultiChatReq)(nil), "wire.MultiChatReq")
	proto.RegisterType((*MultiChatPush)(nil), "wire.MultiChatPush")
	proto.RegisterType((*PushConfirm)(nil), "wire.PushConfirm")
	proto.RegisterType((*PushConfirmAck)(nil), "wire.PushConfirmAck")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6f, 0xd4, 0x3c,
	0x10, 0xc7, 0x95, 0xcd, 0xfb, 0xb4, 0x5d, 0x3d, 0xb2, 0x1e, 0x60, 0x5b, 0x40, 0x5a, 0x45, 0xa8,
	0xac, 0x04, 0xea, 0xa1, 0x9c, 0x41, 0x42, 0xe5, 0x52, 0xb5, 0x88, 0xca, 0x6d, 0xcf, 0x91, 0x49,
	0xbc, 0x59, 0xd3, 0x26, 0x0e, 0x89, 0xd3, 0x92, 0x0f, 0xc3, 0xf7, 0xe0, 0xc4, 0x99, 0x13, 0x9f,
	0x09, 0xf9, 0x25, 0xdb, 0x4d, 0x51, 0xb6, 0x5a, 0x89, 0x9b, 0x67, 0xec, 0xc9, 0xfc, 0x7f, 0x33,
	0x63, 0x07, 0xb6, 0x69, 0x21, 0x98, 0x68, 0x0f, 0xca, 0x8a, 0x0b, 0x8e, 0x9c, 0x5b, 0x56, 0xd1,
	0xbd, 0xed, 0x84, 0xe7, 0x39, 0x2f, 0xb4, 0x2f, 0xfa, 0x02, 0xce, 0x19, 0xa5, 0x15, 0x42, 0xe0,
	0x34, 0x0d, 0x4b, 0x27, 0xd6, 0xd4, 0x9a, 0x85, 0x58, 0xad, 0xd1, 0x1e, 0x04, 0x4d, 0x4d, 0xab,
	0x82, 0xe4, 0x74, 0x32, 0x52, 0xfe, 0xa5, 0x8d, 0x1e, 0x83, 0x97, 0xd2, 0x1b, 0x96, 0xd0, 0x89,
	0x3d, 0xb5, 0x66, 0x2e, 0x36, 0x96, 0x8c, 0x39, 0xe5, 0x09, 0x11, 0x8c, 0x17, 0x13, 0x47, 0xc7,
	0x74, 0x76, 0x74, 0x01, 0xfe, 0x19, 0x69, 0xaf, 0x39, 0x49, 0xd1, 0x2e, 0x04, 0x79, 0x9d, 0xc5,
	0xa2, 0x2d, 0xa9, 0x4a, 0xb9, 0x83, 0xfd, 0xbc, 0xce, 0x2e, 0xda, 0x92, 0xa2, 0x09, 0xf8, 0x09,
	0x2f, 0x04, 0x2d, 0x84, 0x49, 0xda, 0x99, 0xe8, 0x7f, 0x70, 0xe9, 0x37, 0x51, 0x11, 0x95, 0x32,
	0xc4, 0xda, 0x88, 0x62, 0xf0, 0x8f, 0x16, 0x44, 0x60, 0xfa, 0x15, 0x8d, 0x61, 0x24, 0xb8, 0x41,
	0x18, 0x09, 0x8e, 0x9e, 0x42, 0x58, 0x70, 0x11, 0xd7, 0x82, 0x57, 0x9a, 0x20, 0xc0, 0x41, 0xc1,
	0xc5, 0xb9, 0xb4, 0xd1, 0x4b, 0xf0, 0x4b, 0xad, 0x46, 0x7d, 0x6f, 0xeb, 0x70, 0xe7, 0x40, 0xd6,
	0xe7, 0xc0, 0x48, 0xc4, 0xdd, 0x6e, 0xf4, 0x56, 0x27, 0x78, 0x9f, 0x5c, 0xa1, 0x47, 0xe0, 0x49,
	0xd9, 0xa6, 0x4e, 0x36, 0x76, 0xf3, 0x3a, 0x3b, 0x4e, 0x65, 0x9e, 0x9a, 0x16, 0x69, 0x2c, 0x98,
	0xa9, 0x94, 0x8d, 0x03, 0xe9, 0xb8, 0x60, 0x39, 0x8d, 0x7e, 0x58, 0x10, 0xc8, 0xf8, 0xb3, 0xa6,
	0x5e, 0x0c, 0x7d, 0x00, 0x81, 0x33, 0xaf, 0x78, 0x6e, 0x80, 0xd5, 0xda, 0xc0, 0xd8, 0xab, 0x30,
	0x77, 0x49, 0x9c, 0x7e, 0x92, 0x55, 0x18, 0x77, 0x1d, 0x0c, 0x7a, 0x05, 0x61, 0xb2, 0x20, 0x42,
	0x57, 0xde, 0x9b, 0x5a, 0xb3, 0xf1, 0xe1, 0x58, 0x1f, 0x95, 0x1a, 0x65, 0x03, 0x70, 0x90, 0x98,
	0x55, 0xb4, 0x0f, 0x5b, 0x9d, 0x72, 0x49, 0xff, 0x04, 0x7c, 0x2d, 0xbe, 0x9e, 0x58, 0x53, 0x7b,
	0x66, 0x63, 0x4f, 0xa9, 0xaf, 0xa3, 0xdf, 0x06, 0xf1, 0xbc, 0x2d, 0x92, 0x21, 0xc4, 0x5e, 0xe2,
	0xd1, 0xfa, 0xc4, 0x7f, 0xb1, 0xcf, 0x96, 0xd3, 0xe6, 0xa8, 0xc8, 0xff, 0x74, 0xe4, 0x07, 0xe5,
	0x53, 0xb1, 0xdd, 0xfc, 0xf5, 0xaa, 0xe4, 0x0e, 0x57, 0xc9, 0x5b, 0xdb, 0xf2, 0x9f, 0x96, 0x1c,
	0xe3, 0x8c, 0x15, 0x72, 0xaa, 0x9e, 0x03, 0x64, 0x44, 0xd0, 0x5b, 0xd2, 0xc6, 0xcb, 0x0b, 0x12,
	0x1a, 0xcf, 0x71, 0x2a, 0xab, 0x52, 0x52, 0x5a, 0xc9, 0x3d, 0xdd, 0x3e, 0x4f, 0x9a, 0x7a, 0x83,
	0x94, 0x65, 0x7c, 0x45, 0x5b, 0x43, 0xe2, 0x91, 0xb2, 0x3c, 0xa1, 0x6d, 0xef, 0x5e, 0x39, 0xf7,
	0xee, 0xd5, 0x1d, 0xa9, 0xfb, 0x30, 0x69, 0x45, 0x73, 0x2e, 0x68, 0xcc, 0x4a, 0x85, 0x13, 0xe2,
	0x40, 0x3b, 0x8e, 0xcb, 0xe8, 0x9d, 0xd1, 0x6f, 0xda, 0xd6, 0x09, 0xb4, 0x7a, 0x02, 0x77, 0xb5,
	0x8e, 0xb8, 0x59, 0x4a, 0xf7, 0xa5, 0x7d, 0xc9, 0xd2, 0x28, 0x02, 0xff, 0x84, 0x25, 0x57, 0x9f,
	0x1a, 0x31, 0x18, 0x1e, 0xbd, 0x80, 0xf0, 0x94, 0x67, 0xbc, 0x51, 0x57, 0x6f, 0xf0, 0x54, 0x06,
	0xf6, 0x29, 0x4f, 0x56, 0xb8, 0xac, 0x07, 0xb8, 0x06, 0xeb, 0xd9, 0xef, 0x83, 0x7d, 0xaf, 0x0f,
	0xd1, 0x77, 0x0b, 0xb6, 0x3f, 0x36, 0xd7, 0x82, 0x75, 0xaf, 0xc1, 0x33, 0x59, 0xa0, 0x84, 0xb2,
	0x1b, 0x5a, 0xe9, 0x81, 0x0d, 0xf1, 0x9d, 0x63, 0xb3, 0x79, 0xdc, 0x05, 0xb5, 0x56, 0x95, 0xb2,
	0xcd, 0xa3, 0xb4, 0x20, 0xe2, 0x92, 0xa5, 0xab, 0x33, 0xe5, 0xac, 0x9d, 0xa9, 0x5f, 0x16, 0xec,
	0x2c, 0xf5, 0x6d, 0xfa, 0x18, 0xf4, 0xd4, 0xda, 0x1b, 0xa8, 0x75, 0xfa, 0x6a, 0xff, 0xcd, 0xf5,
	0xd8, 0x87, 0x2d, 0x09, 0x70, 0xc4, 0x8b, 0x39, 0xab, 0xf2, 0xe1, 0x77, 0xe1, 0x35, 0x8c, 0x57,
	0xce, 0xc9, 0x59, 0xdc, 0x83, 0x80, 0xcc, 0xe7, 0x34, 0x11, 0x54, 0x43, 0xbb, 0x78, 0x69, 0x7f,
	0xf6, 0xd4, 0x1f, 0xe9, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xd7, 0x86, 0x9e, 0xb5,
	0x06, 0x00, 0x00,
}
