// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namesrv.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LgServer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LgServer) Reset()         { *m = LgServer{} }
func (m *LgServer) String() string { return proto.CompactTextString(m) }
func (*LgServer) ProtoMessage()    {}
func (*LgServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e987583a9e40ddc7, []int{0}
}

func (m *LgServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LgServer.Unmarshal(m, b)
}
func (m *LgServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LgServer.Marshal(b, m, deterministic)
}
func (m *LgServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LgServer.Merge(m, src)
}
func (m *LgServer) XXX_Size() int {
	return xxx_messageInfo_LgServer.Size(m)
}
func (m *LgServer) XXX_DiscardUnknown() {
	xxx_messageInfo_LgServer.DiscardUnknown(m)
}

var xxx_messageInfo_LgServer proto.InternalMessageInfo

func (m *LgServer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LgServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LgServer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Gateway struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             int32    `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ssl                  bool     `protobuf:"varint,5,opt,name=ssl,proto3" json:"ssl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gateway) Reset()         { *m = Gateway{} }
func (m *Gateway) String() string { return proto.CompactTextString(m) }
func (*Gateway) ProtoMessage()    {}
func (*Gateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_e987583a9e40ddc7, []int{1}
}

func (m *Gateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gateway.Unmarshal(m, b)
}
func (m *Gateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gateway.Marshal(b, m, deterministic)
}
func (m *Gateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gateway.Merge(m, src)
}
func (m *Gateway) XXX_Size() int {
	return xxx_messageInfo_Gateway.Size(m)
}
func (m *Gateway) XXX_DiscardUnknown() {
	xxx_messageInfo_Gateway.DiscardUnknown(m)
}

var xxx_messageInfo_Gateway proto.InternalMessageInfo

func (m *Gateway) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gateway) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Gateway) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Gateway) GetProtocol() int32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Gateway) GetSsl() bool {
	if m != nil {
		return m.Ssl
	}
	return false
}

func init() {
	proto.RegisterType((*LgServer)(nil), "wire.LgServer")
	proto.RegisterType((*Gateway)(nil), "wire.Gateway")
}

func init() { proto.RegisterFile("namesrv.proto", fileDescriptor_e987583a9e40ddc7) }

var fileDescriptor_e987583a9e40ddc7 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0xcc, 0x4d,
	0x2d, 0x2e, 0x2a, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0xcf, 0x2c, 0x4a, 0x55,
	0xb2, 0xe3, 0xe2, 0xf0, 0x49, 0x0f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x01, 0xf3, 0x0b, 0x24, 0x98,
	0xa0, 0xfc, 0x02, 0x21, 0x21, 0x2e, 0x96, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d,
	0xd6, 0x20, 0x30, 0x5b, 0x29, 0x9b, 0x8b, 0xdd, 0x3d, 0xb1, 0x24, 0xb5, 0x3c, 0xb1, 0x92, 0x1c,
	0xed, 0x42, 0x52, 0x5c, 0x1c, 0x60, 0xd7, 0x24, 0xe7, 0xe7, 0x48, 0xb0, 0x80, 0xc5, 0xe1, 0x7c,
	0x21, 0x01, 0x2e, 0xe6, 0xe2, 0xe2, 0x1c, 0x09, 0x56, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x10, 0x33,
	0x89, 0x0d, 0x2c, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x9a, 0x8b, 0x43, 0xca, 0x00,
	0x00, 0x00,
}
